name: PatchPro CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
      - name: Run Ruff
        run: ruff check src/patchpro_bot
      - name: Run Semgrep
        run: semgrep --config=semgrep.yml src/patchpro_bot
      - name: Merge Findings
        run: |
          if [ -f scripts/merge_findings.py ]; then
            python scripts/merge_findings.py ruff-findings.json semgrep-findings.json findings.json
          else
            echo '{"findings": []}' > findings.json
          fi
      - name: Upload Findings Artifact
        uses: actions/upload-artifact@v4
        with:
          name: findings
          path: findings.json
      - name: Run PatchPro Bot (CI)
        run: |
          if [ -f src/patchpro_bot/run_ci.py ]; then
            python src/patchpro_bot/run_ci.py
          fi
      - name: Upload PatchPro Report
        uses: actions/upload-artifact@v4
        with:
          name: patchpro-report
          path: artifact/report.md
        if: always()
      - name: Post Sticky PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: artifact/report.md
        if: always()

  test:
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        env:
          PYTHONPATH: patchpro-bot/src
        run: pytest patchpro-bot/tests
